### PR TITLE
Update deprecated use of `crypto:hmac_` functions

### PR DESCRIPTION
**Pull request by dmsnell**
In R23 the `crypto:hmac_` functions are deprecated and will be removed in R24.
In this patch we're introducing a compatability layer so that when compiled
with R22 or newer, where the "new" crypto API was introduced, the `crypto:mac`
functions will be used instead.

When creating this patch I noticed that the call to `crypto:hmac/3` had been
replaced in 267eb2c97c07f7f5bec83c12b36cd6cd3a90d5e5 with a chain of calls to
the version of the functions which update with dynamic data.  It's wasn't clear
to me why that change was made so I didn't undo it, but I have used the single
call in the updated function so create the HMAC in a single step.

## Status

 - I didn't see any version number listed in the repo so I didn't update any version. Looking at the releases on GitHub it looks like this would be ready for *2.0.2* as it doesn't change any interface or functionality.
 - The `CHANGES` file appears to be for CouchDB and not this library so I didn't touch it.
 - Since the list of OTP releases in the `.travis.yml` config are so old I didn't bother changing them. I figured it would possibly be better to do that in another PR where the update to the supported releases could be more intentionally changed.
 - I manually performed a number of tests to compare the results of calling `pbkdf2` before and after this patch and they match as expected.

While working on this I noticed that the `README` shows the wrong calling convention for the library. The code requires a digest function type as the first parameter and this is omitted in the examples. Will update this in another PR.

### CODE REVIEW

**Comment by comtihon** [comment]
Let me fix this build too.

**Comment by comtihon** [comment]
fixed. Please rebase on the latest master

**Comment by dmsnell** [comment]
Rebased and squashed. Thanks again @comtihon

**Comment by comtihon** [comment]
Thanks for the contribution!

**Pull request merged**
